spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase_start
    username: postgres
    password: 123

  liquibase:
    change-log: db/changelog/main-changelog.xml